FROM ruby:3.3-slim

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
      build-essential \
      git \
      curl \
      libpq-dev \
      libyaml-dev \
      libargon2-dev \
      postgresql-client \
    && rm -rf /var/lib/apt/lists/*

ENV BUNDLE_PATH=/usr/local/bundle \
    RAILS_ENV=development \
    BUNDLE_JOBS=4 \
    BUNDLE_RETRY=3

WORKDIR /rails

COPY Gemfile Gemfile.lock ./
RUN bundle install

EXPOSE 3000
CMD ["bin/dev"]
